# Generated by Django 4.2.17 on 2024-12-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Article",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=50, verbose_name="Name")),
                (
                    "desctiption",
                    models.CharField(max_length=250, verbose_name="Desctiption"),
                ),
                ("text", models.TextField(verbose_name="State")),
                ("date", models.DateTimeField(verbose_name="Date")),
            ],
        ),
    ]
